### ISSUE TITLE
一点错误

### ISSUE THREAD

**Issue by dabai-hub** [michaelweixi/Yii2Blog#2]
魏曦老师好，在学习你的教程中，源码出现一点报错，不知道是哪的原因：url指向user模块时，会报错：
Calling unknown method: app\models\UserSearch::find()  在UserSearch的39行。我看了user模型中确实没有find方法，user类实现了IdentityInterface接口，于是在参考手册找到IdentityInterface接口，也没有find方法呀。希望能解答一下，谢谢

**Comment by michaelweixi** [comment]
因为教程没有讲关于授权验证这个部分，所以user部分是没有做的，仅仅是给文章提供了一个作者名而已。user部分最好用advanced模板的，不要在basic模板上改。
